app/models.py
from app import db
from dataclasses import dataclass
from sqlalchemy.inspection import inspect

@dataclass
class User(db.Model):
    """ User Model """
    id: int
    username: str
    password: str

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(15), index=True, unique=True)
    password = db.Column(db.String(20), index=True)
    devices = db.relationship('Device', backref='user', lazy='dynamic')

    def __repr__(self):
        return '<User %r>' % (self.username)

    def __hash__(self):
        return hash(self.id)

@dataclass
class Device(db.Model):
    """ Device Model """
    id: int
    ip_addr: str
    friendly_name: str
    netmiko_driver: str
    device_user: int

    id = db.Column(db.Integer, primary_key=True)
    ip_addr = db.Column(db.String(64), index=True, unique=True)
    friendly_name = db.Column(db.String(64))
    netmiko_driver = db.Column(db.String(64))
    device_user = db.Column(db.Integer, db.ForeignKey('user.id'))
    software_facts = db.relationship('DeviceSoftwareFacts', backref='device_software', uselist=False)
    interface_facts = db.relationship('DeviceInterfaceFacts', backref='device_interfaces')

    def __repr__(self):
        return '<Device %r>' % (self.ip_addr)

    def __hash__(self):
        return hash(self.id)

@dataclass
class DeviceSoftwareFacts(db.Model):
    """ Device Software Facts Model """
    id: int
    version: str
    rommon: str
    hostname: str
    uptime: str
    reload_reason: str
    running_image: str
    hardware: str
    serial: str
    config_register: str
    mac: str
    device: int

    id = db.Column(db.Integer, primary_key=True)
    version = db.Column(db.String())
    rommon = db.Column(db.String())
    hostname = db.Column(db.String())
    uptime = db.Column(db.String())
    reload_reason = db.Column(db.String())
    running_image = db.Column(db.String())
    hardware = db.Column(db.String())
    serial = db.Column(db.String())
    config_register = db.Column(db.String())
    mac = db.Column(db.String())
    device = db.Column(db.Integer, db.ForeignKey('device.id'))

    def __repr__(self):
        return '<DeviceSoftwareFacts %r>' % (self.id)
        
    def __hash__(self):
        return hash(self.id)

@dataclass
class DeviceInterfaceFacts(db.Model):
    """ Device Software Facts Model """
    id: int
    interface: str
    link_status: str
    protocol_status: str
    hardware_type: str
    address: str
    bia: str
    description: str
    ip_address: str
    mtu: str
    duplex: str
    speed: str
    bandwidth: str
    delay: str
    encapsulation: str
    last_input: str
    last_output: str
    last_output_hang: str
    queue_strategy: str
    input_rate: str
    output_rate: str
    input_packets: str
    output_packets: str
    input_errors: str
    output_errors: str
    device: int

    id = db.Column(db.Integer, primary_key=True)
    interface = db.Column(db.String())
    link_status = db.Column(db.String())
    protocol_status = db.Column(db.String())
    hardware_type = db.Column(db.String())
    address = db.Column(db.String())
    bia = db.Column(db.String())
    description = db.Column(db.String())
    ip_address = db.Column(db.String())
    mtu = db.Column(db.String())
    duplex = db.Column(db.String())
    speed = db.Column(db.String())
    bandwidth = db.Column(db.String())
    delay = db.Column(db.String())
    encapsulation = db.Column(db.String())
    last_input = db.Column(db.String())
    last_output = db.Column(db.String())
    last_output_hang = db.Column(db.String())
    queue_strategy = db.Column(db.String())
    input_rate = db.Column(db.String())
    output_rate = db.Column(db.String())
    input_packets = db.Column(db.String())
    output_packets = db.Column(db.String())
    input_errors = db.Column(db.String())
    output_errors = db.Column(db.String())
    device = db.Column(db.Integer, db.ForeignKey('device.id'))

    def __repr__(self):
        return '<DeviceInterfaceFacts %r>' % (self.id)

    def __hash__(self):
        return hash(self.id)

app/forms.py
from flask_wtf import FlaskForm
from app.models import db, User
from app.functions import db_functions, netmiko_functions
from wtforms import StringField, PasswordField, SelectField, SubmitField
from wtforms.validators import DataRequired
from wtforms.ext.sqlalchemy.fields import QuerySelectField

"""
supported_netmiko_devices = [
    ("cisco_ios", "Cisco IOS"),
    ("cisco_asa", "Cisco ASA"),
    ("huawei", "Huawei"),
    ("huawei_smartax", "Huawei SmartAX")]
"""

class UserAddForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Add')

class DeviceAddForm(FlaskForm):
    ip_addr = StringField('IP Address', validators=[DataRequired()])
    friendly_name = StringField('Friendly Name')
    netmiko_driver = SelectField(
        'Netmiko Driver',
        #choices=[netmiko_functions.get_device_types()]
        choices=[(x,x) for x,y in netmiko_functions.get_device_types().items()]
    )
    device_user = QuerySelectField(
        'User',
        get_label='username',
        query_factory=db_functions.db_get_users,
        allow_blank=False
    )
    submit = SubmitField('Add')

app/__init__.py
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from config import Config

app = Flask(__name__)
app.config.from_object(Config)

Bootstrap(app)

db = SQLAlchemy(app)
migrate = Migrate(app, db)

from app.views.api import api, api_users, api_devices
from app.views import devices as devices_routes
from app.views import users as users_routes

from app import models

@app.route("/")
def index():
    return render_template("index.html")

app.register_blueprint(api.bp)
app.register_blueprint(api_users.bp)
app.register_blueprint(api_devices.bp)
app.register_blueprint(devices_routes.bp)
app.register_blueprint(users_routes.bp)

app/views/devices.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from app.functions import db_functions
from app.forms import DeviceAddForm

bp = Blueprint("devices", __name__, url_prefix="/devices")

@bp.route("/")
def devices_home():
    return render_template("devices/index.html", devices=db_functions.db_get_devices())

@bp.route("/add", methods=["GET", "POST"])
def devices_add():
    form = DeviceAddForm()

    if request.method == "GET":
        return render_template("devices/add.html", form=form)
    else:
        if form.validate_on_submit():
            data = {
                "ip_addr": form.ip_addr.data,
                "friendly_name": form.friendly_name.data,
                "netmiko_driver": form.netmiko_driver.data,
                "user" : form.device_user.data
            }

            db_functions.db_add_device(**data)
            flash("Device has been successfully created!")

        return redirect(url_for('devices.devices_home'))

@bp.route("/<int:id>/delete", methods=['GET'])
def devices_delete(id):
    db_functions.db_delete_device(id)
    flash("Device has been successfully deleted!")
    return redirect(url_for('devices.devices_home'))

@bp.route("/<int:id>/view", methods=['GET'])
def devices_view(id):
    device = db_functions.db_get_device(id)
    return render_template ("devices/view.html", device=device)

app/views/users.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from app.functions import db_functions
from app.forms import UserAddForm

bp = Blueprint("users", __name__, url_prefix="/users")

@bp.route("/")
def users_home():
    return render_template("users/index.html", users=db_functions.db_get_users())

@bp.route("/add", methods=["GET", "POST"])
def users_add():
    form = UserAddForm()

    if request.method == "GET":
        return render_template("users/add.html", form=form)
    else:
        if form.validate_on_submit():
            data = {
                "username": form.username.data,
                "password": form.password.data,
            }

            db_functions.db_add_user(**data)
            flash("User has been successfully created!")

        return redirect(url_for('users.users_home'))

@bp.route("/<int:id>/delete", methods=['GET'])
def users_delete(id):
    db_functions.db_delete_user(id)
    flash("User has been successfully deleted!")
    return redirect(url_for('users.users_home'))

app/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>
    {{ field.label }}
</dt><dd>
    {{ field(**kwargs)|safe }}
    {% if field.errors %}
    <ul class="errors">
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</dd>
{% endmacro %}

app/templates/api_index.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-3 ml-2 p-4">
			<h2 class="text-primary">API</h2>
		</div>
	</div>
	<div class="row border rounded p-2 mb-2 bg-light">
		<pre id="api-results">{{ api_results }}</pre>
	</div>
</div>
{% endblock %}

app/templates/base.html
<html>
	<head>
		<meta charset="utf-8">
		<title>{% block title %}{%endblock%} - DB Relationship</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">
	</head>

	{% block navbar %}
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <ul class="navbar-nav">
            <a class="navbar-brand" href="{{ url_for('index') }}">Logo</a>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{{ url_for('users.users_home')}}" id="navbardrop" data-toggle="dropdown">
                  Users
                </a>
                <div class="dropdown-menu">
					<a class="dropdown-item" href="{{ url_for('users.users_add')}}">Add</a>
                	<a class="dropdown-item" href="{{ url_for('users.users_home')}}">View</a>
                </div>
            </li>
            <li class="nav-item dropdown">
            	<a class="nav-link dropdown-toggle" href="{{ url_for('devices.devices_home')}}" id="navbardrop" data-toggle="dropdown">
                  Devices
                </a>
                <div class="dropdown-menu">
					<a class="dropdown-item" href="{{ url_for('devices.devices_add')}}">Add</a>
					<a class="dropdown-item" href="{{ url_for('devices.devices_home')}}">View</a>
                </div>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{{ url_for('api.api_home')}}">API</a>
			</li>
          </ul>
    </nav>
    {% endblock %}

	{% block body %}
	<div class="main">
		<div class="container-fluid">
			{% with messages = get_flashed_messages() %}
			{% if messages %}
				{% for message in messages %}
				<div class="alert alert-info" role="alert">{{ message }}</div>
				{% endfor %}
			{% endif %}
			{% endwith %}

			{% block content %}
			{% endblock %}
		</div>
	</div>

	<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
	{% block scripts %}{% endblock %}
	{% endblock %}
</html>

app/templates/devices/add.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
    Add Device
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-6 ml-3 p-4">
		<h2>Add Device</h2>
		<div style="width: 75%;">
			{% from "_formhelpers.html" import render_field %}
			{{ wtf.quick_form(form) }}
		</div>
	</div>
</div>
{% endblock %}

app/templates/devices/index.html
{% extends "base.html" %}

{% block content %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-9 ml-2 p-4">
				<h2 class="text-primary">Devices</h2>
			</div>
			<div class="table-responsive col-md-12">
                <table class="table table-striped table-hover table-condensed display">
                    <thead>
                        <tr>
							<th>Friendly Name</th>
                            <th>IP Address</th>
							<th>Netmiko Driver</th>
							<th>Device User</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for device in devices %}
                        <tr>
							<td>{{ device.friendly_name }}</td>
                            <td>{{ device.ip_addr }}</td>
							<td>{{ device.netmiko_driver }}</td>
							<td>{{ device.user.username }}</td>
                            <td class="text-center">
                                <a href="{{ url_for('devices.devices_view', id=device.id)}}" class="btn btn-xs btn-success" title="View Device"><i class="far fa-clone" aria-hidden="true"></i></a>
                                <a href="" class="btn btn-xs btn-warning" title="Edit Device"><i class="far fa-edit" aria-hidden="true"></i></a>
                                <a href="{{ url_for('devices.devices_delete', id=device.id)}}"  class="btn btn-xs btn-danger" title="Delete Device"><i class="fas fa-window-close" aria-hidden="true"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
		</div>
	</div>
{% endblock %}

app/templates/devices/view.html
{% extends "base.html" %}

{% block content %}
	<div class="container-fluid">
		<h2 class="text-primary p-2 mt-2 ml-2">{{ device.friendly_name }}</h2>
        <div class="row">
			<div class="card col-md-4 p-4 ml-2 shadow-sm p-4 mb-4 bg-white">
                <h3>Device Details</h3>
                <hr>
                <div id="device_details">
                    <p><strong>IP Address: </strong>{{ device.ip_addr}}</p>
                    <p><strong>Netmiko Driver: </strong>{{ device.netmiko_driver}}</p>
                    <p><strong>User: </strong>{{ device.user.username }} <a href="" class="btn btn-xs btn-warning" title="Edit User"><i class="far fa-edit" aria-hidden="true"></i></a></p>
                </div>
            </div>
            <div class="card col-md-4 p-4 ml-2 shadow-sm p-4 mb-4 bg-white">
                <h3>Software<button id="refreshSoftwareBtn" class="btn btn-sm btn-primary float-right">Refresh</button></h3>
                <hr>
                <div id="device_details">
                    <p id="dd_hostname"><strong>Hostname: </strong>{{ device.software_facts.hostname }}</p>
                    <p id="dd_hardware"><strong>Hardware: </strong>{{ device.software_facts.hardware}}</p>
                    <p id="dd_version"><strong>Version: </strong>{{ device.software_facts.version }}</p>
                    <p id="dd_uptime"><strong>Uptime: </strong>{{ device.software_facts.uptime }}</p>
                    <p id="dd_runningimage"><strong>Image: </strong>{{ device.software_facts.running_image }}</p>
                    <p id="serial"><strong>Serial: </strong>{{ device.software_facts.serial }}</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="card col-md-12 p-4 ml-12 shadow-sm p-4 mb-4 bg-white">
                <h3>Interfaces<button id="getInterfacesBtn" class="btn btn-lg btn-primary float-right">Refresh</button></h3>
                <hr>
                <div class="table-responsive col-md-12">
                    <table id="interfaceTbl" class="table table-striped table-hover table-condensed display">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Link Status</th>
                                <th>Protocol Status</th>
                                <th>Hardware Type</th>
                                <th>Description</th>
                                <th>IP Address</th>
                                <th>MTU</th>
                                <th>Duplex</th>
                                <th>Speed</th>
                                <th>Last Input</th>
                                <th>Last Output</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for interface in device.interface_facts %}
                            <tr>
                                <td>{{ interface.interface }}</td>
                                <td>{{ interface.link_status }}</td>
                                <td>{{ interface.protocol_status }}</td>
                                <td>{{ interface.hardware_type }}</td>
                                <td>{{ interface.description }}</td>
                                <td>{{ interface.ip_address }}</td>
                                <td>{{ interface.mtu }}</td>
                                <td>{{ interface.duplex }}</td>
                                <td>{{ interface.speed }}</td>
                                <td>{{ interface.last_input }}</td>
                                <td>{{ interface.last_output }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <button type="button" id="testBtn" class="btn btn-xs btn-primary">Test</button>

        
{% endblock %}

{%block scripts %}
<script type="text/javascript">
    var $user_id = {{ device.user.id }};
    var $device_id = {{ device.id }};
</script>
<script src="{{ url_for('static', filename='js/devices/view.js') }}"></script>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-md-9 ml-2 p-4">
			<h2 class="text-primary">Index</h2>
		</div>
	</div>
</div>
{% endblock %}

app/templates/users/add.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}
    Add User
{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-6 ml-3 p-4">
		<h2>Add User</h2>
		<div style="width: 75%;">
			{% from "_formhelpers.html" import render_field %}
			{{ wtf.quick_form(form) }}
		</div>
	</div>
</div>
{% endblock %}

app/templates/users/index.html
{% extends "base.html" %}

{% block content %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-9 ml-2 p-4">
				<h2 class="text-primary">Users</h2>
			</div>
			<div class="table-responsive col-md-6">
                <table class="table table-striped table-hover table-condensed display">
                    <thead>
                        <tr>
                            <th>Username</th>
                            <th>Password</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for user in users %}
                        <tr>
                            <td>{{ user.username }}</td>
                            <td>{{ user.password }}</td>
                            <td class="text-center">
                                <a href="" class="btn btn-xs btn-warning" title="Edit User"><i class="far fa-edit" aria-hidden="true"></i></a>
                                <a href="{{ url_for('users.users_delete', id=user.id)}}"  class="btn btn-xs btn-danger" title="Delete User"><i class="fas fa-window-close" aria-hidden="true"></i></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
		</div>
	</div>
{% endblock %}